kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: untitled-bot
  labels:
    app: untitled-bot-174418
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: untitled-bot-174418
    spec:
      containers:
      - name: web
        image: gcr.io/untitled-bot-174418/web:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      - name: bot
        image: gcr.io/untitled-bot-174418/bot:0.0.1
        imagePullPolicy: Always
